Chinese Morphological Analyzer(Chen): cma::SegTagger Class Reference
cma::SegTagger Class Reference
segment the string segment the string using maxent model
#include <CMAPOCTagger.h>
Public Member Functions
SegTagger (const string &cateName, VTrie *posTrie, double eScore=0.7)
void tag_file (const char *inFile, const char *outFile, string encType="gb2312")
void seg_sentence (vector< string > &words, CharType *types, size_t N, size_t retSize, vector< pair< vector< string >, double > > &segment)
void seg_sentence_best (vector< string > &words, CharType *types, vector< string > &segment)
void setCType (CMA_CType *ctype)
void setEScore (double eScore)
double getEScore ()
Static Public Member Functions
static void initialize ()
Detailed Description
segment the string segment the string using maxent model
Constructor & Destructor Documentation
cma::SegTagger::SegTagger (const string & cateName, VTrie * posTrie, double eScore = 0.7)
Create the SegTagger
Parameters:
cateName the poc category name, the model file(cateName + ".model") should exists.
posTrie the VTrie to hold the POS Information
eScore is a double value between 0.5 and 1.0, if the POC tag B has possiblity more the eScore, it will be tagged with E. EScore's default value is 0.7.
References initialize(), and setEScore().
Member Function Documentation
double cma::SegTagger::getEScore () [inline]
Get the EScore
EScore is a double value between 0.5 and 1.0, if the POC tag B has possiblity more the eScore, it will be tagged with E.
EScore's default value is 0.7.
Returns:
the EScore
void cma::SegTagger::initialize () [static]
Would be invoked by the SegTagger's Constructor
Referenced by SegTagger().
void cma::SegTagger::seg_sentence (vector< string > & words, CharType * types, size_t N, size_t retSize, vector< pair< vector< string >, double > > & segment)
tagging given words list and return N best
Parameters:
words the given words list
N return N best
retSize retSize <= N, the size of segment
References cma::POCTagUnit::index, cma::POCTagUnit::pocCode, cma::POCTagUnit::previous, and cma::POCTagUnit::score.
void cma::SegTagger::seg_sentence_best (vector< string > & words, CharType * types, vector< string > & segment)
only return the best segment result, no scores is used here
Parameters:
words the word list
segment to store the segmented words
References cma::pocinner::StrBasedVTrie::completeSearch, cma::pocinner::StrBasedVTrie::exists(), cma::pocinner::StrBasedVTrie::firstSearch(), MAX_PROP_WORD_LEN, and cma::pocinner::StrBasedVTrie::search().
void cma::SegTagger::setEScore (double eScore) [inline]
Set the EScore
EScore is a double value between 0.5 and 1.0, if the POC tag B has possiblity more the eScore, it will be tagged with E.
EScore's default value is 0.7.
Returns:
eScore the new eScore
Referenced by SegTagger().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/source/include/CMAPOCTagger.h
/home/vernkin/projects/chinese-ma-chen/source/src/CMAPOCTagger.cc