Chinese Morphological Analyzer(Chen): cma::CharConditions Class Reference
cma::CharConditions Class Reference
all the conditions of a specific character Each character has at most one CharConditions
#include <cma_ctype_core.h>
Public Member Functions
void setBaseType (CharType baseType)
bool addCondition (Condition &newCondition)
bool addConditions (vector< Condition > &vec)
CharType match (CharType preType, CharValue nextValue, CharType nextType, CharType defaultType=CHAR_TYPE_INIT) const
Public Attributes
CharType baseType_
vector< Condition > conditions_
int conditionSize_
Detailed Description
all the conditions of a specific character Each character has at most one CharConditions
Member Function Documentation
bool cma::CharConditions::addCondition (Condition & newCondition)
If the Condition's type is CHAR_TYPE_OTHER, it would insert as the first element
Returns:
whether add successfully
References conditions_, conditionSize_, cma::Condition::equals(), and cma::Condition::getType().
CharType cma::CharConditions::match (CharType preType, CharValue nextValue, CharType nextType, CharType defaultType = CHAR_TYPE_INIT) const
Get the Proper CharType, if not found, return defaultType
Parameters:
defaultType if not match, return this type
References conditions_, conditionSize_, cma::Condition::match(), and cma::Condition::type_.
Referenced by cma::CMA_CType::getCharType().
Member Data Documentation
CharType cma::CharConditions::baseType_
basis CharType
Referenced by cma::CMA_CType::getCharType().
vector<Condition> cma::CharConditions::conditions_
list of conditions
Referenced by addCondition(), and match().
int cma::CharConditions::conditionSize_
size of the conditions
Referenced by addCondition(), and match().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/source/include/cma_ctype_core.h
/home/vernkin/projects/chinese-ma-chen/source/src/cma_ctype_core.cc