Chinese Morphological Analyzer(Chen): VSynonym Class Reference
VSynonym Class Reference
VSynonym the Param Type of the VSynonymDictionary.
#include <VSynonym.h>
Public Member Functions
VSynonym (uint8_t *start)
void setData (uint8_t *start)
vtnum_t getMatchedCount ()
vtnum_t getSynonymCount (int index)
char * getWord (int index, int offset)
char * getHeadWord (int index)
vtnum_t size ()
void testLoop ()
Friends
ostream & operator<< (ostream &sout, VSynonym &retUnit)
Detailed Description
VSynonym the Param Type of the VSynonymDictionary.
It can hold the Synonym Entry list after query synonym from VSynonymContainer.
Author:
vernkin
Member Function Documentation
char* VSynonym::getHeadWord (int index) [inline]
Return the head word(entry word or first word in a line) which is placed on index. In fact, It is exactly same with getWord(index, 0).
Parameters:
index in range of 0 to getMatchedCount()-1
Returns:
first word in the ith lap.
References getWord().
vtnum_t VSynonym::getMatchedCount () [inline]
Return the count of lines including query used in searching.
Returns:
number of the synonym entries matched
Referenced by size(), and testLoop().
vtnum_t VSynonym::getSynonymCount (int index) [inline]
After calling getMatchedCount(), it is called for iterating whole synonyms within a line. This method won't take bound check.
Parameters:
index in range of 0 to getMatchedCount()-1
Returns:
the num of synonyms in the indexth synonym entry
References VT_NUM_LEN, and VT_OFFSET_LEN.
Referenced by size(), and testLoop().
char* VSynonym::getWord (int index, int offset) [inline]
Return the string which is placed on index and offset. This method won't take bound check
References VT_NUM_LEN, and VT_OFFSET_LEN.
Referenced by getHeadWord(), size(), and testLoop().
vtnum_t VSynonym::size () [inline]
Get the size of the VSynonym
Returns:
the size of the VSynonym
References getMatchedCount(), getSynonymCount(), getWord(), VT_NUM_LEN, and VT_OFFSET_LEN.
void VSynonym::testLoop () [inline]
For testing the speed of iterating all the words
References getMatchedCount(), getSynonymCount(), and getWord().
The documentation for this class was generated from the following file:
/home/vernkin/projects/chinese-ma-chen/source/vsynonym/VSynonym.h