Chinese Morphological Analyzer(Chen): cma::CMA_ME_Analyzer Class Reference
cma::CMA_ME_Analyzer Class Reference
Analyzer for the CMAC.
#include <CMA_ME_Analyzer.h>
Public Types
typedef string OneGramType
Public Member Functions
~CMA_ME_Analyzer ()
virtual void setKnowledge (Knowledge *pKnowledge)
virtual int runWithSentence (Sentence &sentence)
virtual const char * runWithString (const char *inStr)
virtual int runWithStream (const char *inFileName, const char *outFileName)
virtual void getNGramResult (const char *inStr, int n, vector< string > &output)
virtual void getNGramArrayResult (const char *inStr, vector< int > nArray, vector< string > &output)
virtual void splitSentence (const char *paragraph, std::vector< Sentence > &sentences)
virtual void resetIndexPOSList (bool defVal=true)
virtual int setIndexPOSList (std::vector< std::string > &posList)
virtual int getCodeFromStr (const std::string &pos) const
virtual const char * getStrFromCode (int index) const
virtual int getPOSTagSetSize () const
Detailed Description
Analyzer for the CMAC.
Constructor & Destructor Documentation
cma::CMA_ME_Analyzer::~CMA_ME_Analyzer ()
The Desconstrutor won't delete knowledge pointer
Member Function Documentation
virtual int cma::CMA_ME_Analyzer::getCodeFromStr (const std::string & pos) const [virtual]
Get the POS index code from the POS string in the global part-of-speech table.
Parameters:
pos the POS string
Returns:
POS index code, -1 for non POS available
Implements cma::Analyzer.
void cma::CMA_ME_Analyzer::getNGramArrayResult (const char * inStr, vector< int > nArray, vector< string > & output) [virtual]
Get all the specific N-Gram results (see parameter nArray) in the inStr
Parameters:
inStr paragraph string
nArray the collection of the specific n in the N-Gram
output to keep the output value
void cma::CMA_ME_Analyzer::getNGramResult (const char * inStr, int n, vector< string > & output) [virtual]
Get the N-Gram result in the inStr
Parameters:
inStr paragraph string
n the specific n in the N-Gram
output to keep the output value
int cma::CMA_ME_Analyzer::getPOSTagSetSize () const [virtual]
Get the number of POS tags in the global part-of-speech table.
Returns:
the number of POS tags
Implements cma::Analyzer.
References cma::POSTable::size().
const char * cma::CMA_ME_Analyzer::getStrFromCode (int index) const [virtual]
Get the POS string from the POS index code in the global part-of-speech table.
Parameters:
index the POS index code
Returns:
POS string, null pointer for non POS available
Implements cma::Analyzer.
References cma::POSTable::getStrFromCode().
void cma::CMA_ME_Analyzer::resetIndexPOSList (bool defVal = true) [virtual]
Reset all the POS index Information as defVal
Returns:
defVal default value to reset (default is true)
Implements cma::Analyzer.
References cma::POSTable::resetIndexPOSList().
int cma::CMA_ME_Analyzer::runWithSentence (Sentence & sentence) [virtual]
Execute the morphological analysis based on a sentence.
Parameters:
sentence an instance of Sentence
Returns:
0 for fail, 1 for success
Precondition:
the raw sentence string could be got by sentence.getString().
Postcondition:
on successful return, the n-best results could be got by sentence.getListSize(), etc.
Attention:
white-space characters are ignored in the analysis, which include " \t\n\v\f\r", and also space character in specific encoding.
Implements cma::Analyzer.
References cma::Sentence::addList(), cma::POSTable::getCodeFromStr(), cma::Sentence::getListSize(), cma::Sentence::getMorphemeList(), cma::Analyzer::getOption(), cma::Sentence::getScore(), cma::Sentence::getString(), cma::Morpheme::isIndexed, cma::POSTable::isIndexPOS(), cma::CMA_ME_Knowledge::isStopWord(), cma::Morpheme::lexicon_, cma::Analyzer::OPTION_TYPE_NBEST, cma::Analyzer::OPTION_TYPE_POS_TAGGING, cma::Morpheme::posCode_, cma::Morpheme::posStr_, and cma::Sentence::setScore().
int cma::CMA_ME_Analyzer::runWithStream (const char * inFileName, const char * outFileName) [virtual]
Execute the morphological analysis based on a file.
Parameters:
inFileName input file name
outFileName output file name
Returns:
0 for fail, 1 for success
Postcondition:
on successful return, the one-best result is printed to file outFileName.
Implements cma::Analyzer.
References cma::Analyzer::getOption(), cma::CMA_ME_Knowledge::isStopWord(), cma::Analyzer::OPTION_TYPE_POS_TAGGING, cma::Analyzer::posDelimiter_, cma::Analyzer::sentenceDelimiter_, and cma::Analyzer::wordDelimiter_.
const char * cma::CMA_ME_Analyzer::runWithString (const char * inStr) [virtual]
Execute the morphological analysis based on a paragraph string.
Parameters:
inStr paragraph string
Returns:
0 for fail, otherwise a non-zero string pointer for the one-best result
Implements cma::Analyzer.
References cma::Analyzer::getOption(), cma::CMA_ME_Knowledge::isStopWord(), cma::Analyzer::OPTION_TYPE_POS_TAGGING, cma::Analyzer::posDelimiter_, and cma::Analyzer::wordDelimiter_.
int cma::CMA_ME_Analyzer::setIndexPOSList (std::vector< std::string > & posList) [virtual]
Set the POS index as true in the posList
Parameters:
posList the list that allowed in the posList
Returns:
how many POS are set successfully (mainly because not exists).
Implements cma::Analyzer.
References cma::POSTable::setIndexPOSList().
void cma::CMA_ME_Analyzer::setKnowledge (Knowledge * pKnowledge) [virtual]
Set the Knowledge for analysis.
Parameters:
pKnowledge the pointer of Knowledge
Implements cma::Analyzer.
References cma::Knowledge::getEncodeType(), cma::CMA_ME_Knowledge::getPOSTable(), cma::CMA_ME_Knowledge::getPOSTagger(), cma::CMA_ME_Knowledge::getSegTagger(), cma::CMA_ME_Knowledge::getSystemProperty(), cma::CMA_CType::instance(), cma::CMA_ME_Knowledge::isSupportPOS(), cma::Analyzer::OPTION_TYPE_POS_TAGGING, cma::POSTagger::setCType(), cma::Analyzer::setOption(), cma::Analyzer::setPOSDelimiter(), cma::Analyzer::setSentenceDelimiter(), and cma::Analyzer::setWordDelimiter().
void cma::CMA_ME_Analyzer::splitSentence (const char * paragraph, std::vector< Sentence > & sentences) [virtual]
Split a paragraph string into sentences.
Parameters:
paragraph paragraph string
sentences sentence vector
Attention:
the original elements in sentences would not be removed, and the splited sentences are appended into sentences.
Implements cma::Analyzer.
References cma::CTypeTokenizer::assign(), cma::CMA_CType::isSentenceSeparator(), cma::CMA_CType::isSpace(), cma::CTypeTokenizer::next(), and cma::Sentence::setString().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/source/include/CMA_ME_Analyzer.h
/home/vernkin/projects/chinese-ma-chen/source/src/CMA_ME_Analyzer.cc