Chinese Morphological Analyzer(Chen): cma::pocinner::StrBasedVTrie Class Reference
cma::pocinner::StrBasedVTrie Class Reference
The utility class to search the string one by one.
Public Member Functions
StrBasedVTrie (VTrie *pTrie)
void reset ()
bool search (const char *p)
bool firstSearch (const char *p)
bool exists ()
Public Attributes
VTrie * trie
VTrieNode node
bool completeSearch
Detailed Description
The utility class to search the string one by one.
The utility class to search the string one by one
Constructor & Destructor Documentation
cma::pocinner::StrBasedVTrie::StrBasedVTrie (VTrie * pTrie) [inline]
Create an instance
Parameters:
pTrie the VTrie
Member Function Documentation
bool cma::pocinner::StrBasedVTrie::exists () [inline]
Whether exists in the dictionary
References completeSearch, VTrieNode::data, and node.
Referenced by cma::SegTagger::seg_sentence_best().
bool cma::pocinner::StrBasedVTrie::firstSearch (const char * p) [inline]
First reset then search
References reset(), and search().
Referenced by cma::SegTagger::seg_sentence_best().
void cma::pocinner::StrBasedVTrie::reset () [inline]
Reset all the status
References completeSearch, VTrieNode::init(), and node.
Referenced by firstSearch().
bool cma::pocinner::StrBasedVTrie::search (const char * p) [inline]
search the specific string
Parameters:
p point to the specific string
Returns:
true if have extending string or just the right string, here string is the combination of the previous strings and p
References completeSearch, VTrieNode::data, VTrie::find(), VTrieNode::moreLong, node, and trie.
Referenced by firstSearch(), and cma::SegTagger::seg_sentence_best().
Member Data Documentation
bool cma::pocinner::StrBasedVTrie::completeSearch
true if the search over all the characters in the input string
Referenced by exists(), reset(), search(), and cma::SegTagger::seg_sentence_best().
VTrieNode cma::pocinner::StrBasedVTrie::node
The VTrieNode
Referenced by exists(), reset(), and search().
VTrie* cma::pocinner::StrBasedVTrie::trie
The VTrie
Referenced by search().
The documentation for this class was generated from the following file:
/home/vernkin/projects/chinese-ma-chen/source/src/CMAPOCTagger.cc