Chinese Morphological Analyzer(Chen): cma::Analyzer Class Reference
cma::Analyzer Class Reference
Analyzer executes the Chinese morphological analysis.
#include <analyzer.h>
Public Types
enum OptionType { OPTION_TYPE_POS_TAGGING, OPTION_TYPE_NBEST, OPTION_TYPE_NUM }
Public Member Functions
virtual void setKnowledge (Knowledge *pKnowledge)=0
virtual int runWithSentence (Sentence &sentence)=0
virtual const char * runWithString (const char *inStr)=0
virtual int runWithStream (const char *inFileName, const char *outFileName)=0
virtual void getNGramResult (const char *inStr, int n, std::vector< std::string > &output)=0
virtual void getNGramArrayResult (const char *inStr, std::vector< int > nArray, std::vector< std::string > &output)=0
virtual void splitSentence (const char *paragraph, std::vector< Sentence > &sentences)=0
virtual void resetIndexPOSList (bool defVal=true)=0
virtual int setIndexPOSList (std::vector< std::string > &posList)=0
virtual int getCodeFromStr (const std::string &pos) const =0
virtual const char * getStrFromCode (int index) const =0
virtual int getPOSTagSetSize () const =0
void setOption (OptionType nOption, double nValue)
double getOption (OptionType nOption) const
void setPOSDelimiter (const char *delimiter)
const char * getPOSDelimiter () const
void setWordDelimiter (const char *delimiter)
const char * getWordDelimiter () const
void setSentenceDelimiter (const char *delimiter)
const char * getSentenceDelimiter () const
Protected Attributes
std::vector< double > options_
const char * posDelimiter_
const char * wordDelimiter_
const char * sentenceDelimiter_
Detailed Description
Analyzer executes the Chinese morphological analysis.
Analyzer executes the Chinese morphological analysis. Typically, the usage is like below:
// create instances CMA_Factory* factory = CMA_Factory::instance(); Analyzer* analyzer = factory->createAnalyzer(); Knowledge* knowledge = factory->createKnowledge();
// load dictionaries knowledge->loadSystemDict("..."); knowledge->loadUserDict("..."); knowledge->loadStopWordDict("..."); knowledge->loadStatModel("...");
// set knowledge analyzer->setKnowledge(knowledge);
// analyze a sentence Sentence s; s.setString("..."); analyzer->runWithSentence(s); ...
// analyze a paragraph const char* result = analyzer->runWithString("..."); ...
// analyze a file analyzer->runWithStream("...", "...");
delete knowledge; delete analyzer;
Member Enumeration Documentation
enum cma::Analyzer::OptionType
Option type for analysis.
Enumerator:
OPTION_TYPE_POS_TAGGING
the value zero for not to tag part-of-speech tags in the result of runWithSentence(), runWithString() and runWithStream(), which value is 1 defaultly.
OPTION_TYPE_NBEST
a positive value to set the number of candidate results of runWithSentence(), which value is 1 defaultly.
OPTION_TYPE_NUM
the count of option types
Member Function Documentation
virtual int cma::Analyzer::getCodeFromStr (const std::string & pos) const [pure virtual]
Get the POS index code from the POS string in the global part-of-speech table.
Parameters:
pos the POS string
Returns:
POS index code, -1 for non POS available
Implemented in cma::CMA_ME_Analyzer.
virtual void cma::Analyzer::getNGramArrayResult (const char * inStr, std::vector< int > nArray, std::vector< std::string > & output) [pure virtual]
Get all the specific N-Gram results (see parameter nArray) in the inStr
Parameters:
inStr paragraph string
nArray the collection of the specific n in the N-Gram
output to keep the output value
virtual void cma::Analyzer::getNGramResult (const char * inStr, int n, std::vector< std::string > & output) [pure virtual]
Get the N-Gram result in the inStr
Parameters:
inStr paragraph string
n the specific n in the N-Gram
output to keep the output value
double cma::Analyzer::getOption (OptionType nOption) const
Get the option value.
Parameters:
nOption the option type
Returns:
the option value
References options_.
Referenced by cma::CMA_ME_Analyzer::runWithSentence(), cma::CMA_ME_Analyzer::runWithStream(), and cma::CMA_ME_Analyzer::runWithString().
const char * cma::Analyzer::getPOSDelimiter () const
Get the delimiter between word and POS tag in the output result of runWithString() and runWithStream(), which delimiter is "/" defaultly so that the result would be "word/pos word/pos ...".
Returns:
the delimiter between word and POS tag in the output result
References posDelimiter_.
virtual int cma::Analyzer::getPOSTagSetSize () const [pure virtual]
Get the number of POS tags in the global part-of-speech table.
Returns:
the number of POS tags
Implemented in cma::CMA_ME_Analyzer.
const char * cma::Analyzer::getSentenceDelimiter () const
Get the delimiter between sentences.
Returns:
the delimiter between the pairs (word and POS tag) in the output result
References sentenceDelimiter_.
virtual const char* cma::Analyzer::getStrFromCode (int index) const [pure virtual]
Get the POS string from the POS index code in the global part-of-speech table.
Parameters:
index the POS index code
Returns:
POS string, null pointer for non POS available
Implemented in cma::CMA_ME_Analyzer.
const char * cma::Analyzer::getWordDelimiter () const
Get the delimiter between the pairs (word and POS tag) in the output result of runWithString() and runWithStream(), which delimiter is " " (double-space) defaultly so that the result would be "word/pos word/pos ...".
Returns:
the delimiter between the pairs (word and POS tag) in the output result
References wordDelimiter_.
virtual void cma::Analyzer::resetIndexPOSList (bool defVal = true) [pure virtual]
Reset all the POS index Information as defVal
Returns:
defVal default value to reset (default is true)
Implemented in cma::CMA_ME_Analyzer.
virtual int cma::Analyzer::runWithSentence (Sentence & sentence) [pure virtual]
Execute the morphological analysis based on a sentence.
Parameters:
sentence the instance containing the raw sentence string and also to save the analysis result
Returns:
0 for fail, 1 for success
Precondition:
the raw sentence string could be got by sentence.getString().
Postcondition:
on successful return, the n-best results could be got by sentence.getListSize(), etc.
Implemented in cma::CMA_ME_Analyzer.
virtual int cma::Analyzer::runWithStream (const char * inFileName, const char * outFileName) [pure virtual]
Execute the morphological analysis based on a file.
Parameters:
inFileName input file name
outFileName output file name
Returns:
0 for fail, 1 for success
Postcondition:
on successful return, the one-best result is printed to file outFileName.
Implemented in cma::CMA_ME_Analyzer.
Referenced by beginSeg().
virtual const char* cma::Analyzer::runWithString (const char * inStr) [pure virtual]
Execute the morphological analysis based on a paragraph string.
Parameters:
inStr paragraph string
Returns:
0 for fail, otherwise a non-zero string pointer for the one-best result
Implemented in cma::CMA_ME_Analyzer.
virtual int cma::Analyzer::setIndexPOSList (std::vector< std::string > & posList) [pure virtual]
Set the POS index as true in the posList
Parameters:
posList the list that allowed in the posList
Returns:
how many POS are set successfully (mainly because not exists).
Implemented in cma::CMA_ME_Analyzer.
virtual void cma::Analyzer::setKnowledge (Knowledge * pKnowledge) [pure virtual]
Set the Knowledge for analysis.
Parameters:
pKnowledge the pointer of Knowledge
Implemented in cma::CMA_ME_Analyzer.
Referenced by beginSeg().
void cma::Analyzer::setOption (OptionType nOption, double nValue)
Set the option value for analysis.
Parameters:
nOption the option type
nValue the option value
Attention:
when nOption is OPTION_TYPE_NBEST, the invalid nValue less than 1 will take no effect.
References OPTION_TYPE_NBEST, and options_.
Referenced by cma::CMA_ME_Analyzer::setKnowledge().
void cma::Analyzer::setPOSDelimiter (const char * delimiter)
Set the delimiter between word and POS tag in the output result of runWithString() and runWithStream(), which delimiter is "/" defaultly so that the result would be "word/pos word/pos ...".
Parameters:
delimiter the delimiter between word and POS tag in the output result
References posDelimiter_.
Referenced by beginSeg(), and cma::CMA_ME_Analyzer::setKnowledge().
void cma::Analyzer::setSentenceDelimiter (const char * delimiter)
Set the delimiter between sentences, default is empty.
Parameters:
delimiter the delimiter between the pairs (word and POS tag) in the output result
References sentenceDelimiter_.
Referenced by cma::CMA_ME_Analyzer::setKnowledge().
void cma::Analyzer::setWordDelimiter (const char * delimiter)
Set the delimiter between the pairs (word and POS tag) in the output result of runWithString() and runWithStream(), which delimiter is " " (double-space) defaultly so that the result would be "word/pos word/pos ...".
Parameters:
delimiter the delimiter between the pairs (word and POS tag) in the output result
References wordDelimiter_.
Referenced by cma::CMA_ME_Analyzer::setKnowledge().
virtual void cma::Analyzer::splitSentence (const char * paragraph, std::vector< Sentence > & sentences) [pure virtual]
Split a paragraph string into sentences.
Parameters:
paragraph paragraph string
sentences sentence vector
Attention:
the original elements in sentences would not be removed, and the splited sentences are appended into sentences.
Implemented in cma::CMA_ME_Analyzer.
Member Data Documentation
std::vector<double> cma::Analyzer::options_ [protected]
option values
Referenced by getOption(), and setOption().
const char* cma::Analyzer::posDelimiter_ [protected]
the delimiter between word and POS tag in the output result
Referenced by getPOSDelimiter(), cma::CMA_ME_Analyzer::runWithStream(), cma::CMA_ME_Analyzer::runWithString(), and setPOSDelimiter().
const char* cma::Analyzer::sentenceDelimiter_ [protected]
the delimiter between sentences
Referenced by getSentenceDelimiter(), cma::CMA_ME_Analyzer::runWithStream(), and setSentenceDelimiter().
const char* cma::Analyzer::wordDelimiter_ [protected]
the delimiter between the pairs (word and POS tag) in the output result
Referenced by getWordDelimiter(), cma::CMA_ME_Analyzer::runWithStream(), cma::CMA_ME_Analyzer::runWithString(), and setWordDelimiter().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/include/analyzer.h
/home/vernkin/projects/chinese-ma-chen/source/src/analyzer.cpp