ChineseMorphologicalAnalyzer(Chen): maxent::MaxentModel Class Reference
maxent::MaxentModel Class Reference
#include <maxentmodel.hpp>
Public Types
typedef me::feature_type feature_type
typedef me::feature_type outcome_type
typedef std::vector< pair
< feature_type, float > > context_type
Public Member Functions
MaxentModel ()
void load (const string &model)
void save (const string &model, bool binary=false) const
double eval (const context_type &context, const outcome_type &outcome) const
void eval_all (const context_type &context, std::vector< pair< outcome_type, double > > &outcomes, bool sort_result=true) const
outcome_type predict (const context_type &context) const
void begin_add_event ()
void add_event (const context_type &context, const outcome_type &outcome, size_t count=1)
void add_heldout_event (const context_type &context, const outcome_type &outcome, size_t count=1)
void add_event (const vector< string > &context, const outcome_type &outcome, size_t count=1)
void add_heldout_event (const vector< string > &context, const outcome_type &outcome, size_t count=1)
double eval (const vector< string > &context, const outcome_type &outcome) const
void eval_all (const vector< string > &context, std::vector< pair< outcome_type, double > > &outcomes, bool sort_result=true) const
outcome_type predict (const vector< string > &context) const
template<typename Iterator>
void add_events (Iterator begin, Iterator end)
void end_add_event (size_t cutoff=1)
void train (size_t iter=15, const std::string &method="lbfgs", double sigma2=0.0, double tol=1E-05)
void dump_events (const string &model, bool binary=false) const
const char * __str__ () const
Friends
struct maxent_pickle_suite
Classes
struct cmp_outcome
struct cutoffed_event
struct featid_hasher
struct param_hasher
Detailed Description
This class implements a conditional Maximun Entropy Model.
A conditional Maximun Entropy Model (also called log-linear model)has the form: Where x is a context and y is the outcome tag and p(y|x) is the conditional probability.
Normally the context x is composed of a set of contextual predicates.
Constructor & Destructor Documentation
maxent::MaxentModel::MaxentModel ()
Default constructor for MaxentModel.
Construct an empty MaxentModel instance
Member Function Documentation
void maxent::MaxentModel::load (const string & model)
Load a MaxentModel from a file.
Parameters:
model The name of the model to load
Referenced by cma::POSTagger::POSTagger().
void maxent::MaxentModel::save (const string & model, bool binary = false) const
Save a MaxentModel to a file.
Parameters:
model The name of the model to save.
binary If true, the file is saved in binary format, which is usually smaller (if compiled with libz) and much faster to load.
double maxent::MaxentModel::eval (const context_type & context, const outcome_type & outcome) const
Evaluates a context, return the conditional probability p(y|x).
This method calculates the conditional probability p(y|x) for given x and y.
Parameters:
context A list of pair<string, double> indicates names of the contextual predicates and their values which are to be evaluated together.
outcome The outcome label for which the conditional probability is calculated.
Returns:
The conditional probability of p(outcome|context).
See also:
eval_all()
Referenced by eval().
void maxent::MaxentModel::eval_all (const context_type & context, std::vector< pair< outcome_type, double > > & outcomes, bool sort_result = true) const
Evaluates a context, return the conditional distribution of the context.
This method calculates the conditional probability p(y|x) for each possible outcome tag y.
Parameters:
context A list of pair<string, double> indicates the contextual predicates and their values (must be >= 0) which are to be evaluated together.
outcomes An array of the outcomes paired with it's probability predicted by the model (the conditional distribution).
sort_result Whether or not the returned outcome array is sorted (larger probability first). Default is true.
TODO: need optimized for large number of outcomes
See also:
eval()
Referenced by eval_all(), and predict().
MaxentModel::outcome_type maxent::MaxentModel::predict (const context_type & context) const
Evaluates a context, return the most possible outcome y for given context x
This function is a thin wrapper for
See also:
eval_all().
Parameters:
context A list of String names of the contextual predicates which are to be evaluated together.
Returns:
The most possible outcome label for given context.
See also:
eval_all()
References eval_all().
Referenced by predict().
void maxent::MaxentModel::begin_add_event ()
Signal the begining of adding event (the start of training).
This method must be called before adding any event to the model. It informs the model the beginning of training. After the last event is added
See also:
end_add_event() must be called to indicate the ending of adding events.
void maxent::MaxentModel::add_event (const context_type & context, const outcome_type & outcome, size_t count = 1)
Add an event (context, outcome, count) to current model for training later.
add_event() should be called after calling
See also:
begin_add_event().
Parameters:
context A std::vector of pair<std::string, float> to indicate the context predicates and their values (must be >= 0) occured in the event.
outcome A std::string indicates the outcome label.
count How many times this event occurs in training set. default = 1
Referenced by add_event(), and add_events().
void maxent::MaxentModel::add_event (const vector< string > & context, const outcome_type & outcome, size_t count = 1)
Add an event (context, outcome, count) to model for training later.
This function is a thin wrapper for the above
See also:
eval(), with all feature values omitted (default to 1.0, which is binary feature case).
add_event() should be called after calling
See also:
begin_add_event().
Parameters:
context A list string names of the context predicates occure in the event. The feature value defaults to 1.0 (binary feature)
outcome A std::string indicates the outcome label.
count How many times this event occurs in training set. default = 1
References add_event().
double maxent::MaxentModel::eval (const vector< string > & context, const outcome_type & outcome) const
Evaluates a context, return the conditional probability p(y|x).
This method calculates the conditional probability p(y|x) for given x and y.
This is a wrapper function for the above
See also:
eval(), omitting feature values in paramaters (default to 1.0, treated as binary case)
Parameters:
context A list of string names of the contextual predicates to be evaluated together.
outcome The outcome label for which the conditional probability is calculated.
Returns:
The conditional probability of p(outcome|context).
See also:
eval_all()
References eval().
void maxent::MaxentModel::eval_all (const vector< string > & context, std::vector< pair< outcome_type, double > > & outcomes, bool sort_result = true) const
Evaluates a context, return the conditional distribution of given context.
This method calculates the conditional probability p(y|x) for each possible outcome tag y.
This function is a thin warpper for the above
See also:
eval_all() feature values are omitted (defualt to 1.0) for binary feature value case.
Parameters:
context A list of string names of the contextual predicates which are to be evaluated together.
outcomes an array of the outcomes paired with it's probability predicted by the model (the conditional distribution).
sort_result Whether or not the returned outcome array is sorted (larger probability first). Default is true.
TODO: need optimized for large number of outcomes
See also:
eval()
References eval_all().
MaxentModel::outcome_type maxent::MaxentModel::predict (const vector< string > & context) const
Evaluates a context, return the most possible outcome y for given context x
This function is a thin wrapper for
See also:
predict() for binary value case (omitting feature values which default to 1.0)
Parameters:
context A list of String names of the contextual predicates which are to be evaluated together.
Returns:
The most possible outcome label for given context.
See also:
eval_all()
References predict().
template<typename Iterator> void maxent::MaxentModel::add_events (Iterator begin, Iterator end) [inline]
Add a set of events indicated by range [begin, end). the value type of Iterator must be pair<context_type, outcome_type>
References add_event().
void maxent::MaxentModel::end_add_event (size_t cutoff = 1)
Signal the ending of adding events.
This method must be called after adding of the last event to inform the model the ending of the adding events.
Parameters:
cutoff Event cutoff, all events that occurs less than cutoff times will be discussed. Default = 1 (remain all events). Please note this is different from the usual sense of *feature cutoff*.
void maxent::MaxentModel::train (size_t iter = 15, const std::string & method = "lbfgs", double sigma2 = 0.0, double tol = 1E-05)
Train a ME model using selected training method.
This is a wapper function for the underline Trainer class. It will create corresponding Trainer object to train a Conditional MaxentModel. Currently L-BFGS and GIS are implemented.
Parameters:
iter Specify how many iterations are need for iterative methods. Default is 15 iterations.
method The training method to use. Can be "lbfgs" or "gis". L-BFGS is used as the default training method.
sigma2 Global variance in Gaussian prior smoothing. Default is 0, which turns off Gaussian smoothing.
tol Tolerance for detecting model convergence. A model is regarded as convergence when . Default tol = 1-E05
The documentation for this class was generated from the following files:
source/maxent/maxentmodel.hpp
source/maxent/maxentmodel.cpp