Chinese Morphological Analyzer(Chen): cma::CMA_WType Class Reference
cma::CMA_WType Class Reference
CMA_WType gives the word type information.
#include <cma_wtype.h>
Public Types
enum WordType {
WORD_TYPE_NUMBER = 1, WORD_TYPE_DATE, WORD_TYPE_LETTER, WORD_TYPE_PUNC,
WORD_TYPE_OTHER
}
Public Member Functions
CMA_WType (const CMA_CType *ctype)
WordType getWordType (const char *word)
WordType getWordType (CharType *types, size_t begin, size_t size)
Detailed Description
CMA_WType gives the word type information.
Member Enumeration Documentation
enum cma::CMA_WType::WordType
Word type.
Enumerator:
WORD_TYPE_NUMBER
number word, example: 632, 三百八十
WORD_TYPE_DATE
date word, example: 2009年, 二零零九年, 5月, 6日
WORD_TYPE_LETTER
letter word, example: Pentium4
WORD_TYPE_OTHER
other word
Constructor & Destructor Documentation
cma::CMA_WType::CMA_WType (const CMA_CType * ctype)
Constructor.
Parameters:
ctype reference to the specific character encoding
Member Function Documentation
CMA_WType::WordType cma::CMA_WType::getWordType (CharType * types, size_t begin, size_t size)
Get the word type.
Parameters:
types types that are already knows
begin index in types
the size of the types
Returns:
the word type.
References WORD_TYPE_DATE, WORD_TYPE_LETTER, WORD_TYPE_NUMBER, and WORD_TYPE_OTHER.
CMA_WType::WordType cma::CMA_WType::getWordType (const char * word)
Get the word type.
Parameters:
word pointer to the word string
Returns:
the word type.
References cma::CTypeTokenizer::assign(), cma::CMA_CType::getCharType(), cma::CTypeTokenizer::next(), WORD_TYPE_DATE, WORD_TYPE_LETTER, WORD_TYPE_NUMBER, and WORD_TYPE_OTHER.
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/source/include/cma_wtype.h
/home/vernkin/projects/chinese-ma-chen/source/src/cma_wtype.cpp