Chinese Morphological Analyzer(Chen): VSynonymContainer Class Reference
VSynonymContainer Class Reference
the VTrie version of the Synonym Dictionary
#include <VSynonym.h>
Public Member Functions
VSynonymContainer ()
VSynonymContainer (string nameFile, const char *sep_synonyms=",", const char *sep_words="_")
void setSynonymDelimiter (const char *delim)
void setWordDelimiter (const char *delim)
void get_synonyms (const string &key, VSynonym &synonym)
void searchNgetSynonym (char *query, VSynonym *synonym)
VSynonym * get_synonyms (const string &key)
VExpandedQuery * expandQuery (const string &query)
VTrie * getData ()
int loadSynonyms (const char *pathDic)
size_t size ()
Static Public Attributes
static const size_t MinLen = 5
Detailed Description
the VTrie version of the Synonym Dictionary
The class keep the relation between the synonym and macthed synonym lists. VTrie is used to hold the all the synonyms, and a extra array to hold all the synonym entry lists.
Author:
Vernkin
Constructor & Destructor Documentation
VSynonymContainer::VSynonymContainer () [inline]
Create the PHSynonymCntainer with default synonym delimiter (',') and word delimiter ('_')
References setSynonymDelimiter(), and setWordDelimiter().
VSynonymContainer::VSynonymContainer (string nameFile, const char * sep_synonyms = ",", const char * sep_words = "_") [inline]
Create the PHSynonymCntainer with specific synonym and word delimiter, and the resource file
Parameters:
nameFile specific synonym resource file, each line is a synonym, each synonym is separated by sep_synonyms in a synonym, and each individal word is separated by sep_synonyms in a synonym entry.
sep_synonyms synonym entry delimiter in a synonym
sep_words word delimiter in a synonym entry
References loadSynonyms(), setSynonymDelimiter(), and setWordDelimiter().
Member Function Documentation
VExpandedQuery* VSynonymContainer::expandQuery (const string & query) [inline]
Expand the query with all the possible synonyms
References VExpandedQuery::addUnit(), get_synonyms(), and size().
VSynonym* VSynonymContainer::get_synonyms (const string & key) [inline]
Get the synonyms with specific key, if found nothing, return NULL.
Parameters:
key specific key to find the synonyms
Returns:
synonym VSynonym object to store the data; return NULL if the key is not exists.
References VTrieNode::data, and VTrie::search().
void VSynonymContainer::get_synonyms (const string & key, VSynonym & synonym) [inline]
Get the synonyms with specific key, if found nothing, data in the PHSynonym is set NULL.
Parameters:
key specific key to find the synonyms
synonym PHSynonym object to store the data
References VTrieNode::data, VTrie::search(), and VSynonym::setData().
Referenced by expandQuery(), and cma::CMA_ME_Knowledge::getSynonyms().
int VSynonymContainer::loadSynonyms (const char * pathDic) [inline]
load the data from the file
Parameters:
pathDic the path of the synonym dictionary file
Returns:
0 if occur error and 1 if works fine
References VTrieNode::data, VTrieNode::init(), VTrie::insert(), MinLen, and VTrie::search().
Referenced by VSynonymContainer().
void VSynonymContainer::searchNgetSynonym (char * query, VSynonym * synonym) [inline]
Search the query from VSynonymContainer. if searching fail, assign 0 or NULL to synonym parameter. otherwise, synonym parameter has a proper value.
Parameters:
query word to be queried
synonym to store the returned information
References VTrieNode::data, VTrie::search(), and VSynonym::setData().
void VSynonymContainer::setSynonymDelimiter (const char * delim) [inline]
Set the synonym delimiter
Parameters:
delim new synonym delimiter
Referenced by VSynonymContainer().
void VSynonymContainer::setWordDelimiter (const char * delim) [inline]
Set the word delimiter
Parameters:
delim new word delimiter
Referenced by VSynonymContainer().
size_t VSynonymContainer::size () [inline]
Get the size of the whole VSynonymContainer used
References VTrie::size().
Referenced by expandQuery().
Member Data Documentation
const size_t VSynonymContainer::MinLen = 5 [static]
The Mininum Length starts to record for the length map
Referenced by loadSynonyms().
The documentation for this class was generated from the following file:
source/vsynonym/VSynonym.h