Chinese Morphological Analyzer(Chen): cma::Sentence Class Reference
cma::Sentence Class Reference
Sentence saves the results of Chinese morphological analysis.
#include <sentence.h>
Public Member Functions
Sentence ()
Sentence (const char *pString)
void setString (const char *pString)
const char * getString (void) const
int getListSize (void) const
int getCount (int nPos) const
const char * getLexicon (int nPos, int nIdx) const
bool isIndexWord (int nPos, int nIdx) const
int getPOS (int nPos, int nIdx) const
const char * getStrPOS (int nPos, int nIdx) const
const MorphemeList * getMorphemeList (int nPos) const
double getScore (int nPos) const
void setScore (int nPos, double nScore)
int getOneBestIndex (void) const
void addList (const MorphemeList &morphemeList, double score=0.0)
Detailed Description
Sentence saves the results of Chinese morphological analysis.
Sentence saves the results of Chinese morphological analysis. Typically, the usage is like below:
Sentence s; s.setString("...");
Analyzer* analyzer = ...; analyzer->runWithSentence(s);
// get n-best results for(int i=0; i<s.getListSize(); ++i) { for(int j=0; j<s.getCount(i); ++j) { const char* pLexicon = s.getLexicon(i, j); const char* strPOS = s.getStrPOS(i, j); ... } double score = s.getScore(i); ... }
// get one-best result int i= s.getOneBestIndex(); ...
Constructor & Destructor Documentation
cma::Sentence::Sentence ()
Default Constructor and do nothing
cma::Sentence::Sentence (const char * pString)
Constructor with initial raw sentence string
Parameters:
pString value of the raw string
Member Function Documentation
void cma::Sentence::addList (const MorphemeList & morphemeList, double score = 0.0)
Add a candidate result of morphological analysis.
Parameters:
morphemeList the candidate result
score the score value of the candidate
Referenced by cma::CMA_ME_Analyzer::runWithSentence().
int cma::Sentence::getCount (int nPos) const
Get the number of morphemes in candidate result nPos.
Parameters:
nPos candidate result index
Returns:
the number of morphemes
const char * cma::Sentence::getLexicon (int nPos, int nIdx) const
Get the string of morpheme nIdx in candidate result nPos.
Parameters:
nPos candidate result index
nIdx morpheme index
Returns:
morpheme string
int cma::Sentence::getListSize (void) const
Get the number of candidates of morphological analysis result.
Returns:
the number of candidates
Referenced by cma::CMA_ME_Analyzer::runWithSentence().
const MorphemeList * cma::Sentence::getMorphemeList (int nPos) const
Get the MorphemeList of candidate result nPos.
Parameters:
nPos candidate result index
Returns:
the MorphemeList
Referenced by cma::CMA_ME_Analyzer::runWithSentence().
int cma::Sentence::getOneBestIndex (void) const
Get the index of the candidate result, which has the highest score.
Returns:
candidate result index, -1 is returned if there is no candidate result.
int cma::Sentence::getPOS (int nPos, int nIdx) const
Get the POS index code of morpheme nIdx in candidate result nPos.
Parameters:
nPos candidate result index
nIdx morpheme index
Returns:
POS index code, -1 for non POS available
double cma::Sentence::getScore (int nPos) const
Get the score of candidate result nPos.
Parameters:
nPos candidate result index
Returns:
the score value
Referenced by cma::CMA_ME_Analyzer::runWithSentence().
const char * cma::Sentence::getString (void) const
Get the raw sentence string.
Returns:
value of the raw string
Referenced by cma::CMA_ME_Analyzer::runWithSentence().
const char * cma::Sentence::getStrPOS (int nPos, int nIdx) const
Get the POS string of morpheme nIdx in candidate result nPos.
Parameters:
nPos candidate result index
nIdx morpheme index
Returns:
POS string, null pointer for non POS available
bool cma::Sentence::isIndexWord (int nPos, int nIdx) const
Get the string of morpheme nIdx in candidate result nPos.
Parameters:
nPos candidate result index
nIdx morpheme index
Returns:
morpheme string
void cma::Sentence::setScore (int nPos, double nScore)
Set the score of candidate result nPos.
Parameters:
nPos candidate result index
nScore the score value
Referenced by cma::CMA_ME_Analyzer::runWithSentence().
void cma::Sentence::setString (const char * pString)
Set the raw sentence string.
Parameters:
pString value of the raw string
Attention:
the previous analysis results will be removed.
Referenced by cma::CMA_ME_Analyzer::splitSentence().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/include/sentence.h
/home/vernkin/projects/chinese-ma-chen/source/src/sentence.cpp