Chinese Morphological Analyzer(Chen): cma::POSTable Class Reference
cma::POSTable Class Reference
POSTable stores the global table of part-of-speech tags.
#include <pos_table.h>
Public Types
enum POSType {
POS_TYPE_NUMBER, POS_TYPE_DATE, POS_TYPE_FOREIGN, POS_TYPE_PUNCT,
POS_TYPE_USER, POS_TYPE_MAX_NUM
}
typedef std::vector< std::pair
< std::string, bool > > POSTableInfo
Public Member Functions
int addPOS (const std::string &pos)
int getCodeFromStr (const std::string &pos) const
const char * getStrFromCode (int index) const
int size () const
int getCodeFromType (POSType type) const
bool isIndexPOS (int posCode) const
bool setIndexPOS (int posCode, bool isIndex)
void resetIndexPOSList (bool defVal=true)
int setIndexPOSList (std::vector< std::string > &posList)
const POSTableInfo * getPOSTableInfo ()
Detailed Description
POSTable stores the global table of part-of-speech tags.
POSTable stores the global table of part-of-speech tags, each tag includes a string value and its index code. Note that the string value of part-of-speech tag is case-insensitive. For example, 'Ng' equals to 'ng'.
Member Enumeration Documentation
enum cma::POSTable::POSType
Special part-of-speech types.
Enumerator:
POS_TYPE_NUMBER
the POS type of numeral words, such as "123", "一百", etc
POS_TYPE_DATE
the POS type of temporal nouns such as "今天", "2009年", etc
POS_TYPE_FOREIGN
the POS type of foreign words such as "ISO", "ＣＨＩＮＡ", etc
POS_TYPE_PUNCT
the POS type of punctuations such as "，", "。", etc
POS_TYPE_USER
the POS type of user defined words
POS_TYPE_MAX_NUM
the count of POS types
Member Function Documentation
int cma::POSTable::addPOS (const std::string & pos)
Add the POS string to the global part-of-speech table.
Parameters:
pos the POS string
Returns:
the index code of the POS string added, if the POS string has been added before, its index code previously added is returned.
Attention:
Note that the POS string is case-insensitively.
Referenced by cma::CMA_ME_Knowledge::loadPOSModel().
int cma::POSTable::getCodeFromStr (const std::string & pos) const
Get the POS index code from the POS string in the global part-of-speech table.
Parameters:
pos the POS string
Returns:
POS index code, -1 for non POS available
Referenced by cma::CMA_ME_Analyzer::runWithSentence().
int cma::POSTable::getCodeFromType (POSType type) const
Get the POS index code from the special POS type.
Parameters:
type the POS type
Returns:
POS index code, -1 for non POS available
const POSTableInfo* cma::POSTable::getPOSTableInfo () [inline]
Get POSTable information, reserved Interface
Returns:
POSTable information
const char * cma::POSTable::getStrFromCode (int index) const
Get the POS string from the POS index code in the global part-of-speech table.
Parameters:
index the POS index code
Returns:
POS string, null pointer for non POS available
Referenced by cma::CMA_ME_Analyzer::getStrFromCode().
bool cma::POSTable::isIndexPOS (int posCode) const
Whether the posCode indicates that word is index word, if the posCode is invalid, return true.
Parameters:
posCode the specific pos Code
Returns:
true if posCode is the index POS
Referenced by cma::CMA_ME_Analyzer::runWithSentence().
void cma::POSTable::resetIndexPOSList (bool defVal = true)
Reset all the pos index Information as defVal
Returns:
defVal default value to reset (default is true)
Referenced by cma::CMA_ME_Analyzer::resetIndexPOSList().
bool cma::POSTable::setIndexPOS (int posCode, bool isIndex)
Set the specific posCode whether is index
Parameters:
posCode the specific POS code
whether the index is posCode
Returns:
whether set successfully, if false, the posCode doesn't exists
int cma::POSTable::setIndexPOSList (std::vector< std::string > & posList)
Set the POS index as true in the posList
Parameters:
posList the list that allowed in the posList
Returns:
how many POS are set successfully (mainly because not exists).
Referenced by cma::CMA_ME_Analyzer::setIndexPOSList().
int cma::POSTable::size () const
Get the number of POS tags in the global part-of-speech table.
Returns:
the number of POS tags
Referenced by cma::CMA_ME_Analyzer::getPOSTagSetSize().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/source/include/pos_table.h
/home/vernkin/projects/chinese-ma-chen/source/src/pos_table.cpp