Chinese Morphological Analyzer(Chen): VTrie Class Reference
VTrie Class Reference
VTrie is a variant of the Radix Tree.
#include <VTrie.h>
Public Member Functions
int insert (const char *key, VTrieNode *node)
void optimize ()
int search (const char *key, VTrieNode *node)
int find (char ch, VTrieNode *node)
size_t size ()
Detailed Description
VTrie is a variant of the Radix Tree.
While the Radix Tree is a space-optimized standard trie, the VTrie is a space-optimized of the Radix Tree.
Author:
vernkin
Member Function Documentation
int VTrie::find (char ch, VTrieNode * node) [inline]
The function of this method is to iterate trie node by each character. Parameter (VTrieNode*)node is including current node state.
Parameters:
ch specific character
node the last VTrieNode
Returns:
If following node does not exist, return value is 0, other wise bigger than 0.
References VTrieNode::data, VTrieNode::moreLong, VTrieNode::offset, VTrieNode::state, VTCHILDS_L, and VTENTRY_L.
Referenced by cma::pocinner::StrBasedVTrie::search().
int VTrie::insert (const char * key, VTrieNode * node) [inline]
If insert failed, return 0, otherwise any value bigger than 0 And the information of a current trie node is set to node parameter.
Parameters:
key the key
node the node to stote the information
Returns:
return 0 if insert fails
References VTrieNode::data, VTrieNode::moreLong, VTCHILDS_L, VTENTRY_L, and VTSAMEPS_L.
Referenced by cma::POSTagger::appendWordPOS(), and VSynonymContainer::loadSynonyms().
void VTrie::optimize () [inline]
Optimize the data structure of the VTrie, it makes querying faster and use less memory.
References VTCHILDS_L, and VTKEY_NUM.
int VTrie::search (const char * key, VTrieNode * node) [inline]
If string is not found, return 0, otherwise any value bigger than 0. And the information of a searched trie node is set to node parameter.
Parameters:
key the key
node the node to stote the information
Returns:
return 0 if search fails
References VTrieNode::data, VTrieNode::moreLong, VTCHILDS_L, and VTENTRY_L.
Referenced by cma::POSTagger::appendWordPOS(), VSynonymContainer::get_synonyms(), VSynonymContainer::loadSynonyms(), and VSynonymContainer::searchNgetSynonym().
size_t VTrie::size () [inline]
Get the size of the structure
Referenced by VSynonymContainer::size().
The documentation for this class was generated from the following file:
/home/vernkin/projects/chinese-ma-chen/source/vsynonym/VTrie.h