Chinese Morphological Analyzer(Chen): cma::POSTagger Class Reference
cma::POSTagger Class Reference
Tagging the POS Information Tagging the POS using the maxent model.
#include <CMAPOSTagger.h>
Public Member Functions
POSTagger (const string &model, VTrie *pTrie)
POSTagger (const string &model, const char *dictFile)
void tag_file (const char *inFile, const char *outFile)
void tag_sentence (vector< string > &words, size_t N, size_t retSize, vector< pair< vector< string >, double > > &segment)
void tag_sentence_best (vector< string > &words, vector< string > &posRet, int begin, int end)
double tag_word_best (vector< string > &words, vector< string > &poses, int index, string &pos)
void setCType (CMA_CType *ctype)
bool appendWordPOS (string &line)
Public Attributes
vector< set< string > > posVec_
string defaultPOS
string numberPOS
string letterPOS
string puncPOS
string datePOS
Detailed Description
Tagging the POS Information Tagging the POS using the maxent model.
Constructor & Destructor Documentation
cma::POSTagger::POSTagger (const string & model, VTrie * pTrie)
Construct the POSTagger with outer VTrie
Parameters:
model POS model name
References posVec_.
cma::POSTagger::POSTagger (const string & model, const char * dictFile)
Construct the POSTagger with inner VTrie (read from dictFile)
References appendWordPOS(), and posVec_.
Member Function Documentation
bool cma::POSTagger::appendWordPOS (string & line)
Append the POS Information into Trie and POS Vector
Parameters:
line a line like: word1 pos1 pos2 ... posN
Returns:
whether add successfully
References VTrieNode::data, VTrie::insert(), posVec_, and VTrie::search().
Referenced by POSTagger().
void cma::POSTagger::setCType (CMA_CType * ctype) [inline]
Set the reference to the specific character encoding
Parameters:
ctype new specific character encoding
Referenced by cma::CMA_ME_Analyzer::setKnowledge().
void cma::POSTagger::tag_file (const char * inFile, const char * outFile)
Tag the segmented file with pos (In UTF8 Encoding)
Parameters:
inFile the input file
outFile the output file
References tag_sentence_best().
void cma::POSTagger::tag_sentence (vector< string > & words, size_t N, size_t retSize, vector< pair< vector< string >, double > > & segment)
tagging given words list and return N best
Parameters:
words the given words list
N return N best
retSize retSize <= N, the size of segment
to store the result value
References cma::POSTagUnit::index, cma::POSTagUnit::pos, cma::POSTagUnit::previous, and cma::POSTagUnit::score.
void cma::POSTagger::tag_sentence_best (vector< string > & words, vector< string > & posRet, int begin, int end)
Only return the best result
Parameters:
words words vector
posRet to hold the result value
begin the begin index (include) to check
end the first index that should not check
Referenced by tag_file().
double cma::POSTagger::tag_word_best (vector< string > & words, vector< string > & poses, int index, string & pos)
tag the word with the best POS and return its score
Parameters:
words words vector
poses the previous pos vector, but the current pos won't store into the poses
index the current index to check
pos to store the best pos
Returns:
return the score of the best pos
Member Data Documentation
string cma::POSTagger::datePOS
Date POS
Referenced by cma::CMA_ME_Knowledge::loadPOSModel().
string cma::POSTagger::defaultPOS
default POS
Referenced by cma::CMA_ME_Knowledge::loadPOSModel().
string cma::POSTagger::letterPOS
Letter POS
Referenced by cma::CMA_ME_Knowledge::loadPOSModel().
string cma::POSTagger::numberPOS
Number POS
Referenced by cma::CMA_ME_Knowledge::loadPOSModel().
vector<set<string> > cma::POSTagger::posVec_
vector to hold the POS information
Referenced by appendWordPOS(), and POSTagger().
string cma::POSTagger::puncPOS
Punctuation POS
Referenced by cma::CMA_ME_Knowledge::loadPOSModel().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/source/include/CMAPOSTagger.h
/home/vernkin/projects/chinese-ma-chen/source/src/CMAPOSTagger.cc