Chinese Morphological Analyzer(Chen): cma::CMA_ME_Knowledge Class Reference
cma::CMA_ME_Knowledge Class Reference
Knowledge for the CMAC.
#include <CMA_ME_Knowledge.h>
Public Member Functions
virtual int loadSystemDict (const char *binFileName)
virtual int loadUserDict (const char *fileName)
virtual int loadSynonymDictionary (const char *fileName)
virtual void getSynonyms (const string &word, VSynonym &synonym)
virtual int loadStopWordDict (const char *fileName)
virtual int loadStatModel (const char *cateName)
virtual int loadPOSModel (const char *cateName)
virtual int loadConfig (const char *fileName)
virtual int encodeSystemDict (const char *txtFileName, const char *binFileName)
virtual int loadModel (const char *encoding, const char *modelPath)
virtual bool isSupportPOS () const
SegTagger * getSegTagger () const
POSTagger * getPOSTagger () const
bool isStopWord (const string &word)
VTrie * getTrie ()
POSTable * getPOSTable () const
POSTable * getPOSTable ()
const string * getSystemProperty (const string &key)
Detailed Description
Knowledge for the CMAC.
Member Function Documentation
int cma::CMA_ME_Knowledge::encodeSystemDict (const char * txtFileName, const char * binFileName) [virtual]
Encode the system dictionary file from text to binary format.
Parameters:
txtFileName the text file name
binFileName the binary file name
Returns:
0 for fail, 1 for success
Implements cma::Knowledge.
POSTable * cma::CMA_ME_Knowledge::getPOSTable ()
Get POSTable
POSTable * cma::CMA_ME_Knowledge::getPOSTable () const
Get POSTable
Referenced by cma::CMA_ME_Analyzer::setKnowledge().
POSTagger * cma::CMA_ME_Knowledge::getPOSTagger () const
Get the segment tagger.
Returns:
pointer to tagger
Referenced by cma::CMA_ME_Analyzer::setKnowledge().
SegTagger * cma::CMA_ME_Knowledge::getSegTagger () const
Get the segment tagger.
Returns:
pointer to tagger
Referenced by cma::CMA_ME_Analyzer::setKnowledge().
void cma::CMA_ME_Knowledge::getSynonyms (const string & word, VSynonym & synonym) [virtual]
Get the Synonyms of the specific word
Parameters:
word the specific word
synonym the object to hold the synonym
References VSynonymContainer::get_synonyms().
const string * cma::CMA_ME_Knowledge::getSystemProperty (const string & key)
Get System Property
Parameters:
key the name of that system property
Returns:
if not exists, return 0.
Referenced by cma::CMA_ME_Analyzer::setKnowledge().
VTrie * cma::CMA_ME_Knowledge::getTrie ()
Get the VTrie that Knowledge holds
Returns:
the VTrie that Knowledge holds
bool cma::CMA_ME_Knowledge::isStopWord (const string & word)
Whether the specific word is stop word
Referenced by cma::CMA_ME_Analyzer::runWithSentence(), cma::CMA_ME_Analyzer::runWithStream(), and cma::CMA_ME_Analyzer::runWithString().
bool cma::CMA_ME_Knowledge::isSupportPOS () const [virtual]
Whether contains POS model
Returns:
true if contains POS model
Implements cma::Knowledge.
Referenced by cma::CMA_ME_Analyzer::setKnowledge().
int cma::CMA_ME_Knowledge::loadConfig (const char * fileName) [virtual]
Load the configuration file, which is in text format. This file contains the configuration used in morphological analysis, such as part-of-speech configuration, etc.
Parameters:
fileName the file name
Returns:
0 for fail, 1 for success
Implements cma::Knowledge.
Referenced by loadModel().
int cma::CMA_ME_Knowledge::loadModel (const char * encoding, const char * modelPath) [virtual]
Auto load POS model, Stat Model and System Dictionaries. Encoding must be set here. like gb18030 and utf8 the directory that contains all the models
Returns:
whether perform success
Implements cma::Knowledge.
References cma::Knowledge::decodeEncodeType(), cma::Knowledge::ENCODE_TYPE_NUM, loadConfig(), loadPOSModel(), loadStatModel(), loadUserDict(), and cma::Knowledge::setEncodeType().
int cma::CMA_ME_Knowledge::loadPOSModel (const char * cateName) [virtual]
Load the model file in binary format, which contains statistical information for part-of-speech tagging.
Parameters:
cateName the file name, it include two files, (cateName).model and (cateName).tag. For example, with cateName cate1, "cate1.model" and "cate1.tag" should exists
Returns:
0 for fail, 1 for success
Implements cma::Knowledge.
References cma::POSTable::addPOS(), cma::POSTagger::datePOS, cma::POSTagger::defaultPOS, cma::POSTagger::letterPOS, cma::POSTagger::numberPOS, and cma::POSTagger::puncPOS.
Referenced by loadModel().
int cma::CMA_ME_Knowledge::loadStatModel (const char * cateName) [virtual]
Load the model file in binary format, which contains statistical information for word segmentation.
Parameters:
cateName the file name, it include two files, (cateName).model and (cateName).tag. For example, with cateName cate1, "cate1.model" and "cate1.tag" should exists
Returns:
0 for fail, 1 for success
Implements cma::Knowledge.
References cma::Knowledge::getEncodeType(), cma::CMA_CType::instance(), and cma::CMA_CType::loadConfiguration().
Referenced by loadModel().
int cma::CMA_ME_Knowledge::loadStopWordDict (const char * fileName) [virtual]
Load the stop-word dictionary file, which is in text format. The words in this file are ignored in the morphological analysis result.
Parameters:
fileName the file name
Returns:
0 for fail, 1 for success
Implements cma::Knowledge.
int cma::CMA_ME_Knowledge::loadSynonymDictionary (const char * fileName) [virtual]
Load the synonym dictionary
Parameters:
fileName the file name
Returns:
0 for fail, 1 for success
int cma::CMA_ME_Knowledge::loadSystemDict (const char * binFileName) [virtual]
Load the system dictionary file, which is in binary format.
Parameters:
binFileName the file name
Returns:
0 for fail, 1 for success
Implements cma::Knowledge.
int cma::CMA_ME_Knowledge::loadUserDict (const char * fileName) [virtual]
Load the user dictionary file, which is in text format.
Parameters:
fileName the file name
Returns:
0 for fail, 1 for success
Implements cma::Knowledge.
Referenced by loadModel().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/source/include/CMA_ME_Knowledge.h
/home/vernkin/projects/chinese-ma-chen/source/src/CMA_ME_Knowledge.cc