Chinese Morphological Analyzer(Chen): cma::Knowledge Class Reference
cma::Knowledge Class Reference
Knowledge manages the linguistic information for Chinese morphological analysis.
#include <knowledge.h>
Public Types
enum EncodeType {
ENCODE_TYPE_GB2312, ENCODE_TYPE_BIG5, ENCODE_TYPE_GB18030, ENCODE_TYPE_UTF8,
ENCODE_TYPE_NUM
}
Public Member Functions
virtual int loadSystemDict (const char *binFileName)=0
virtual int loadUserDict (const char *fileName)=0
virtual int loadStopWordDict (const char *fileName)=0
virtual int loadStatModel (const char *binFileName)=0
virtual int loadPOSModel (const char *binFileName)=0
virtual int loadConfig (const char *fileName)=0
virtual int encodeSystemDict (const char *txtFileName, const char *binFileName)=0
void setEncodeType (EncodeType type)
EncodeType getEncodeType () const
virtual int loadModel (const char *encoding, const char *modelPath)=0
virtual bool isSupportPOS () const =0
Static Public Member Functions
static Knowledge::EncodeType decodeEncodeType (const char *encType)
Detailed Description
Knowledge manages the linguistic information for Chinese morphological analysis.
Member Enumeration Documentation
enum cma::Knowledge::EncodeType
Encode type of characters.
Enumerator:
ENCODE_TYPE_GB2312
GB 2312 character type.
ENCODE_TYPE_BIG5
Big 5 character type.
ENCODE_TYPE_GB18030
GB18030 character type.
ENCODE_TYPE_UTF8
UTF8 character type.
ENCODE_TYPE_NUM
the count of character types
Member Function Documentation
Knowledge::EncodeType cma::Knowledge::decodeEncodeType (const char * encType) [static]
Get the encoding type by the encode type string
Parameters:
encType encode type string
Returns:
assicated Knowledge::EncodeType in the class Knowledge
References ENCODE_TYPE_BIG5, ENCODE_TYPE_GB18030, ENCODE_TYPE_GB2312, ENCODE_TYPE_NUM, and ENCODE_TYPE_UTF8.
Referenced by cma::CMA_ME_Knowledge::loadModel().
virtual int cma::Knowledge::encodeSystemDict (const char * txtFileName, const char * binFileName) [pure virtual]
Encode the system dictionary file from text to binary format.
Parameters:
txtFileName the text file name
binFileName the binary file name
Returns:
0 for fail, 1 for success
Implemented in cma::CMA_ME_Knowledge.
Knowledge::EncodeType cma::Knowledge::getEncodeType () const
Get the character encode type.
Returns:
the encode type
Referenced by cma::CMA_ME_Knowledge::loadStatModel(), and cma::CMA_ME_Analyzer::setKnowledge().
virtual bool cma::Knowledge::isSupportPOS () const [pure virtual]
Whether contains POS model
Returns:
true if contains POS model
Implemented in cma::CMA_ME_Knowledge.
virtual int cma::Knowledge::loadConfig (const char * fileName) [pure virtual]
Load the configuration file, which is in text format. This file contains the configuration used in morphological analysis, such as part-of-speech configuration, etc.
Parameters:
fileName the file name
Returns:
0 for fail, 1 for success
Implemented in cma::CMA_ME_Knowledge.
virtual int cma::Knowledge::loadModel (const char * encoding, const char * modelPath) [pure virtual]
Auto load POS model, Stat Model and System Dictionaries. Encoding must be set here. like gb18030 and utf8 the directory that contains all the models
Returns:
whether perform success
Implemented in cma::CMA_ME_Knowledge.
Referenced by beginSeg().
virtual int cma::Knowledge::loadPOSModel (const char * binFileName) [pure virtual]
Load the model file in binary format, which contains statistical information for part-of-speech tagging.
Parameters:
binFileName the file name
Returns:
0 for fail, 1 for success
Implemented in cma::CMA_ME_Knowledge.
virtual int cma::Knowledge::loadStatModel (const char * binFileName) [pure virtual]
Load the model file in binary format, which contains statistical information for word segmentation.
Parameters:
binFileName the file name
Returns:
0 for fail, 1 for success
Implemented in cma::CMA_ME_Knowledge.
virtual int cma::Knowledge::loadStopWordDict (const char * fileName) [pure virtual]
Load the stop-word dictionary file, which is in text format. The words in this file are ignored in the morphological analysis result.
Parameters:
fileName the file name
Returns:
0 for fail, 1 for success
Implemented in cma::CMA_ME_Knowledge.
virtual int cma::Knowledge::loadSystemDict (const char * binFileName) [pure virtual]
Load the system dictionary file, which is in binary format.
Parameters:
binFileName the file name
Returns:
0 for fail, 1 for success
Implemented in cma::CMA_ME_Knowledge.
virtual int cma::Knowledge::loadUserDict (const char * fileName) [pure virtual]
Load the user dictionary file, which is in text format.
Parameters:
fileName the file name
Returns:
0 for fail, 1 for success
Implemented in cma::CMA_ME_Knowledge.
void cma::Knowledge::setEncodeType (EncodeType type)
Set the character encode type. If this function is not called, the default value returned by getEncodeType() is ENCODE_TYPE_GB2312.
Parameters:
type the encode type
Referenced by cma::CMA_ME_Knowledge::loadModel().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/include/knowledge.h
/home/vernkin/projects/chinese-ma-chen/source/src/knowledge.cpp