Chinese Morphological Analyzer(Chen): cma::CMA_CType Class Reference
cma::CMA_CType Class Reference
#include <cma_ctype.h>
Public Member Functions
virtual ~CMA_CType ()
virtual unsigned int getByteCount (const char *p) const =0
CharType getCharType (const char *p, CharType preType, const char *nextP) const
CharType getBaseType (const char *p) const
bool isPunct (const char *p) const
size_t length (const char *p) const
unsigned int getEncodeValue (const char *p) const
bool isSpace (const char *p) const
bool isSentenceSeparator (const char *p) const
int loadConfiguration (const char *file)
CharType getDefaultEndType (CharType preType)
string getPOCXmlStr (const char *p) const
Static Public Member Functions
static CMA_CType * instance (Knowledge::EncodeType type)
static CharType getCharTypeByXmlName (const char *name, bool noDefault=false)
Protected Attributes
Knowledge::EncodeType type_
Detailed Description
CMA_CType gives the character type information.
Constructor & Destructor Documentation
cma::CMA_CType::~CMA_CType () [virtual]
Destructor
Member Function Documentation
CharType cma::CMA_CType::getBaseType (const char * p) const
Get the base Character Type of Character P without any rules
Parameters:
p the input character
Returns:
the base type of p, or CHAR_TYPE_OTHER for default
References getEncodeValue().
virtual unsigned int cma::CMA_CType::getByteCount (const char * p) const [pure virtual]
Get the byte count of the first character pointed by p, which character is in a specific encoding.
Parameters:
p pointer to the character string
Returns:
true for punctuation, false for non punctuation.
Implemented in cma::CMA_CType_Big5, cma::CMA_CType_GB18030, cma::CMA_CType_GB2312, and cma::CMA_CType_UTF8.
Referenced by getEncodeValue(), length(), and cma::CTypeTokenizer::next().
CharType cma::CMA_CType::getCharType (const char * p, CharType preType, const char * nextP) const
Get the character type.
Parameters:
p pointer to the string to be checked
preType the chartype of the previous character
nextP the pointer of the next character, it can be 0
Returns:
the character type.
References getEncodeValue().
Referenced by cma::CMA_WType::getWordType(), isPunct(), and cma::CateStrTokenizer::next().
CharType cma::CMA_CType::getCharTypeByXmlName (const char * name, bool noDefault = false) [static]
The naming in the poc.xml, include digit, chardigit, space, letter, punctuation
Parameters:
noDefault if true, an assert error will occur
Returns:
if not found, return CHAR_TYPE_OTHER
CharType cma::CMA_CType::getDefaultEndType (CharType preType)
Invoke this function when the last word not exists
Parameters:
preType type of the previous character
Returns:
the default next type
unsigned int cma::CMA_CType::getEncodeValue (const char * p) const
Get the encoding value in unsigned int type
param p the character with pointer p
Returns:
unsigned int value of p, 0 if error occurs
References getByteCount().
Referenced by getBaseType(), getCharType(), isSentenceSeparator(), and isSpace().
string cma::CMA_CType::getPOCXmlStr (const char * p) const
Get the specific string with associated encoding in the poc.xml Except for utf-16, others encoding return the original form
Parameters:
p the input string
Returns:
the target string
References type_.
CMA_CType * cma::CMA_CType::instance (Knowledge::EncodeType type) [static]
Create an instance of CMA_CType based on the character encode type.
Parameters:
type the character encode type
Returns:
the pointer to instance
References cma::Knowledge::ENCODE_TYPE_BIG5, cma::Knowledge::ENCODE_TYPE_GB18030, cma::Knowledge::ENCODE_TYPE_GB2312, and cma::Knowledge::ENCODE_TYPE_UTF8.
Referenced by cma::CMA_ME_Knowledge::loadStatModel(), and cma::CMA_ME_Analyzer::setKnowledge().
bool cma::CMA_CType::isPunct (const char * p) const
Whether the p is a punctuation
Parameters:
p pointer to the string to be checked
Returns:
true if the p is the punctuation
References getCharType().
bool cma::CMA_CType::isSentenceSeparator (const char * p) const
Check whether is a seperator of sentence.
Parameters:
p pointer to the character string
Returns:
true for separator, false for non separator.
References getEncodeValue().
Referenced by cma::CMA_ME_Analyzer::splitSentence().
bool cma::CMA_CType::isSpace (const char * p) const
Check whether is white-space character. White-space characters are " \t\n\v\f\r", and also space character in specific encoding.
Parameters:
p pointer to the character string
Returns:
true for white-space character, false for non white-space character.
References getEncodeValue().
Referenced by cma::CMA_ME_Analyzer::splitSentence().
size_t cma::CMA_CType::length (const char * p) const
Get the number of the characters in the p
Parameters:
p pointer to the string to be checked
Returns:
the number of the characters in the p
References getByteCount().
int cma::CMA_CType::loadConfiguration (const char * file)
Load the poc.xml
Returns:
1 if load successfully
Referenced by cma::CMA_ME_Knowledge::loadStatModel().
Member Data Documentation
Knowledge::EncodeType cma::CMA_CType::type_ [protected]
The encode type of the current cma_ctype class
Referenced by cma::CMA_CType_Big5::CMA_CType_Big5(), cma::CMA_CType_GB18030::CMA_CType_GB18030(), cma::CMA_CType_GB2312::CMA_CType_GB2312(), cma::CMA_CType_UTF8::CMA_CType_UTF8(), and getPOCXmlStr().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/source/include/cma_ctype.h
/home/vernkin/projects/chinese-ma-chen/source/src/cma_ctype.cpp