Chinese Morphological Analyzer(Chen): cma::CateStrTokenizer Class Reference
cma::CateStrTokenizer Class Reference
Category String Tokenizier.
#include <CateStrTokenizer.h>
Public Member Functions
CateStrTokenizer (CTypeTokenizer *pCToken)
bool next ()
bool isWordSeq ()
vector< string > & getWordSeq ()
CharType getType ()
string & getSpecialStr ()
Detailed Description
Category String Tokenizier.
Segment the string based on the char types, line letters, digits and so on
Author:
vernkin
Constructor & Destructor Documentation
cma::CateStrTokenizer::CateStrTokenizer (CTypeTokenizer * pCToken)
Create an instance
References cma::CTypeTokenizer::getCType().
Member Function Documentation
string & cma::CateStrTokenizer::getSpecialStr ()
Get the special string if the current token is not with type CHAR_TYPE_OTHER
CharType cma::CateStrTokenizer::getType ()
Get the type of the current token
Returns:
the type of the current token
vector< string > & cma::CateStrTokenizer::getWordSeq ()
Get the words vector
Returns:
the words vector
bool cma::CateStrTokenizer::isWordSeq ()
Whether is word sequence, the another possibility is sepecial string,. Like letters, digits and so on
Returns:
if true invoke getWordSeq(), else invoke
bool cma::CateStrTokenizer::next ()
Move to next token
Returns:
if false their is not any more token
References cma::CMA_CType::getCharType(), and cma::CTypeTokenizer::next().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/source/include/CateStrTokenizer.h
/home/vernkin/projects/chinese-ma-chen/source/src/CateStrTokenizer.cc