Chinese Morphological Analyzer(Chen): cma::CTypeTokenizer Class Reference
cma::CTypeTokenizer Class Reference
Tokenizer tokenizes a raw input string in specific encoding to a sequence of characters.
#include <tokenizer.h>
Public Member Functions
CTypeTokenizer (const CMA_CType *ctype)
CTypeTokenizer (const CMA_CType *ctype, const char *str)
const CMA_CType * getCType () const
void assign (const char *str)
const char * next ()
Detailed Description
Tokenizer tokenizes a raw input string in specific encoding to a sequence of characters.
Tokenizer tokenizes a raw input string in specific encoding to a sequence of characters. Typically, the usage is like below:
// create instance of encoding type CMA_CType* ctype = CMA_CType_GB2312::instance();
// create instance of Tokenizer Tokenizer tokenizer(*ctype);
// set the raw input string tokenizer.assign("...");
// get each character for(const char* p=tokenizer.next(); p; p=tokenizer.next()) { // print the character cout << p << endl; }
Constructor & Destructor Documentation
cma::CTypeTokenizer::CTypeTokenizer (const CMA_CType * ctype)
Constructor.
Parameters:
ctype reference to the specific character encoding
Member Function Documentation
void cma::CTypeTokenizer::assign (const char * str)
Set a raw input string.
Parameters:
str pointer to the raw input string
Attention:
The raw input string should be encoded in ctype of Constructor. As Tokenizer doesn't make a copy of str, the caller must ensure the life time of str in the calling of next() afterward.
Referenced by cma::CMA_WType::getWordType(), and cma::CMA_ME_Analyzer::splitSentence().
const CMA_CType* cma::CTypeTokenizer::getCType () const [inline]
Get the reference to the specific character encoding
Returns:
reference to the specific character encoding
Referenced by cma::CateStrTokenizer::CateStrTokenizer().
const char * cma::CTypeTokenizer::next ()
Get the next character in specific encoding.
Returns:
pointer to the next character
Attention:
0 is returned if there is no character left.
References cma::CMA_CType::getByteCount().
Referenced by cma::CMA_WType::getWordType(), cma::CateStrTokenizer::next(), and cma::CMA_ME_Analyzer::splitSentence().
The documentation for this class was generated from the following files:
/home/vernkin/projects/chinese-ma-chen/source/include/tokenizer.h
/home/vernkin/projects/chinese-ma-chen/source/src/tokenizer.cpp