Chinese Morphological Analyzer(Chen): source/include/SeggerCMD.h File Reference
source/include/SeggerCMD.h File Reference
the CMD tool for the Segger
#include <iostream>
#include "cma_factory.h"
#include "analyzer.h"
#include "knowledge.h"
#include "sentence.h"
#include "cma_ctype.h"
#include "VTimer.h"
Functions
void beginSeg (string mate, string inFile, string outFile, string enc, string posDelimiter)
int seggerEntry (int argc, char **argv)
void printSeggerUsage ()
Detailed Description
the CMD tool for the Segger
Author:
vernkin
Function Documentation
void beginSeg (string mate, string inFile, string outFile, string enc, string posDelimiter)
To segment the file
References cma::CMA_Factory::createAnalyzer(), cma::CMA_Factory::createKnowledge(), cma::Knowledge::loadPOSModel(), cma::Knowledge::loadStatModel(), cma::Knowledge::loadUserDict(), cma::Analyzer::runWithStream(), cma::Knowledge::setEncodeType(), cma::Analyzer::setKnowledge(), cma::Analyzer::setOption(), and cma::Analyzer::setPOSDelimiter().