#ifndef ICMA_VERSION_H
#define ICMA_VERSION_H

#define ICMA_VERSION_MAJOR @CPACK_PACKAGE_VERSION_MAJOR@
#define ICMA_VERSION_MINOR @CPACK_PACKAGE_VERSION_MINOR@
#define ICMA_VERSION_PATCH @CPACK_PACKAGE_VERSION_PATCH@

#define ICMA_VERSION "@CPACK_PACKAGE_VERSION_MAJOR@.@CPACK_PACKAGE_VERSION_MINOR@.@CPACK_PACKAGE_VERSION_PATCH@"

#endif